In [1]:
import numpy as np

In [2]:
np.convolve([1,2,3,4], [6,7,8,9])

array([ 6, 19, 40, 70, 70, 59, 36])

In [3]:
sequence1 = np.array([1, 2, 3, 4])
sequence2 = np.array([6, 7, 8, 9])

In [4]:
print(sequence1)
print(sequence2)

[1 2 3 4]
[6 7 8 9]


In [6]:
dft_sequence1 = np.fft.fft(sequence1)
dft_sequence2 = np.fft.fft(sequence2)

In [7]:
print(dft_sequence1)
print(dft_sequence2)

[10.+0.j -2.+2.j -2.+0.j -2.-2.j]
[30.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [8]:
Y = dft_sequence1*dft_sequence2
print(Y)

[300.+0.j   0.-8.j   4.-0.j   0.+8.j]


In [10]:
print(np.real(np.fft.ifft(Y)))

[76. 78. 76. 70.]


In [19]:
import numpy as np

# Dãy số
sequence1 = np.array([1, 2, 3, 4])
sequence2 = np.array([6, 7, 8, 9])

# Kích thước tổng cộng cho tích chập
N = len(sequence1) + len(sequence2) - 1

# Tính DFT
dft_sequence1 = np.fft.fft(sequence1, n=N)
dft_sequence2 = np.fft.fft(sequence2, n=N)
print(dft_sequence1)
print(dft_sequence2)

# Nhân các kết quả DFT
convolution_dft = dft_sequence1 * dft_sequence2
print(convolution_dft)
# Tính IDFT của kết quả
convolution_result = np.fft.ifft(convolution_dft)

# In kết quả
print("Tích chập (IDFT của DFT) của hai dãy:", np.real(convolution_result))


[10.        +0.j         -2.02445867-6.22398166j  0.34601074+2.47912132j
  0.17844793-2.42198468j  0.17844793+2.42198468j  0.34601074-2.47912132j
 -2.02445867+6.22398166j]
[30.         +0.j          0.47554133-17.17719733j
  2.84601074 +3.68305787j  2.67844793 -5.55688552j
  2.67844793 +5.55688552j  2.84601074 -3.68305787j
  0.47554133+17.17719733j]
[ 300.         +0.j         -107.87327487+31.81476553j
   -8.14599703 +8.32998346j  -12.9807281  -7.4787746j
  -12.9807281  +7.4787746j    -8.14599703 -8.32998346j
 -107.87327487-31.81476553j]
Tích chập (IDFT của DFT) của hai dãy: [ 6. 19. 40. 70. 70. 59. 36.]
